%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\b-ric\rankingcandidates.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/12 17:09:37

%% Initialize variables.
filename = 'C:\Users\b-ric\rankingcandidates.dat';
delimiter = ',';

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
A = [dataArray{1:end-1}];

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
[m,n]=size(A);
M=zeros(5,5);
M2=zeros(5,5);
a=.85;
maxit=100000;
for i=1:m
    
    if strcmp(A(i,1),'HC')
        M(:,1)=1/n*ones(n,1)';
    elseif strcmp(A(i,1),'BS')
        M(:,2)=1/n*ones(n,1)';
    elseif strcmp(A(i,1),'JK')
        M(:,3)=1/n*ones(n,1)';
    elseif strcmp(A(i,1),'TC')
        M(:,4)=1/n*ones(n,1)';
    elseif strcmp(A(i,1),'DT')
        M(:,4)=1/n*ones(n,1)';
    end
        
    if strcmp(A(i,2),'HC')
        M(:,1)=[1,0,0,0,0]';
    elseif strcmp(A(i,2),'BS')
        M(:,2)=[1,0,0,0,0]';
    elseif strcmp(A(i,2),'JK')
        M(:,3)=[1,0,0,0,0]';
    elseif strcmp(A(i,2),'TC')
        M(:,4)=[1,0,0,0,0]';
    elseif strcmp(A(i,2),'DT')
        M(:,5)=[1,0,0,0,0]';
    end
        
    if strcmp(A(i,3),'HC')
       M(:,1)=[1/2,1/2,0,0,0]';
    elseif strcmp(A(i,3),'BS')
       M(:,2)=[1/2,1/2,0,0,0]';
    elseif strcmp(A(i,3),'JK')
       M(:,3)=[1/2,1/2,0,0,0]';
    elseif strcmp(A(i,3),'TC')
       M(:,4)=[1/2,1/2,0,0,0]';
    elseif strcmp(A(i,3),'DT')
       M(:,5)=[1/2,1/2,0,0,0]';
    end
    
    if strcmp(A(i,4),'HC')
       M(:,1)=[1/3,1/3,1/3,0,0]';
    elseif strcmp(A(i,4),'BS')
       M(:,2)=[1/3,1/3,1/3,0,0]';
    elseif strcmp(A(i,4),'JK')
       M(:,3)=[1/3,1/3,1/3,0,0]';
    elseif strcmp(A(i,4),'TC')
       M(:,4)=[1/3,1/3,1/3,0,0]';
    elseif strcmp(A(i,4),'DT')
       M(:,5)=[1/3,1/3,1/3,0,0]';
    end
    
    if strcmp(A(i,5),'HC')
       M(:,1)=[1/4,1/4,1/4,1/4,0]';
    elseif strcmp(A(i,5),'BS')
       M(:,2)=[1/4,1/4,1/4,1/4,0]';
    elseif strcmp(A(i,5),'JK')
       M(:,3)=[1/4,1/4,1/4,1/4,0]';
    elseif strcmp(A(i,5),'TC')
       M(:,4)=[1/4,1/4,1/4,1/4,0]';
    elseif strcmp(A(i,5),'DT')
       M(:,5)=[1/4,1/4,1/4,1/4,0]';
    end
    M=a*M+(1-a)/n*ones(n,n);
    M2=M+M2;
end
M=1/240*M2;

w=1/n*ones(n,1);
for k=1:maxit
    w=M*w;
    
end
format long;
w

